### ISSUE TITLE
moderation mvp

### ISSUE THREAD

**Issue by substack** [cabal-club/commons#10]
list of tasks for minimal viable moderation feature. edit this post to assign yourself a task or to move tasks around.

tasks for user testing:

- [ ] `/hide` works in channels + cabal-wide
- [x] `/share` share modkey - cblgh https://github.com/cabal-club/cabal-client/pull/50
- [x] add modkey to cli title - cblgh https://github.com/cabal-club/cabal-cli/pull/190
- [x] refactor cabal-core to handle mods & admins in the modkey url (`cabal://<key>?mod=aaa&admin=111`) - cblgh [cabal-core/#85](https://github.com/cabal-club/cabal-core/pull/85)
- [x] `cabal-client`: improve event emitting for slash-commands - cblgh https://github.com/cabal-club/cabal-client/pull/50
- [x] desktop: connect context menu to hide action - nick
- [x] desktop: connect context menu to set admin/moderator action - nick
- [x] desktop: logic to hide messages - nick
- [x] invoke moderation help with `/moderation` - cblgh

tasks for feature demo / initial release:

- [x] figure out syntax for the slash commands - cblgh, [gist](https://gist.github.com/cblgh/19562550a3512d8c50ecf30f3c4c32e7)
- [x] cabal-core moderation view to support `cabal.modKeys` and `cabal.adminKeys` - substack ([cabal-core/#86](https://github.com/cabal-club/cabal-core/pull/86))
- [x] `/inspect` to see what actions a potential moderator / admin has done - substack ([cabal-core/#87](https://github.com/cabal-club/cabal-core/pull/87), [cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [ ] desktop: ui to show user mod/admin history - nick
- [x] hide messages from hidden users in cli - kira ([cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [x] add admin/moderator labels in cli - kira ([cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [x] applied moderation actions are visible in UIs (`shittyTroll was hidden by cblgh, reason: shitty troll`) -cblgh https://github.com/cabal-club/cabal-cli/pull/192  https://github.com/cabal-club/cabal-client/pull/52
- [x] desktop: add admin/moderator labels
- [x] cabal-client
   -  [x] query for all mod info on startup - kira
    - [x] listen for events from moderation view + update users - kira ([cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [x] materialized-group-auth array flags - substack
- [x] materialized-group-auth - event for capturing "skips" and role changes - substack
- [x] materialized-group-auth list() to get actions across all channels - substack
- [x] update core to use materialized-group-auth with flags - substack ([cabal-core/#83](https://github.com/cabal-club/cabal-core/pull/83))
- [x] core/clients?: prevent creating channel called "@" - substack ([cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [x] solve hyperswarm connection issues
- [x] make a video demo for mozilla (just in case) - nick

tasks for after the demo:

- [ ] https://github.com/cabal-club/cabal-core/issues/91
- [x] command to see applied hides (/modlist?) - /hides in ([cabal-client/#39](https://github.com/cabal-club/cabal-client/pull/39))
- [ ] write human friendly documentation for website
- [x] write cabal-client API docs for moderation class - cblgh https://github.com/cabal-club/cabal-client/issues/51
- [ ] write low level/white paper-esque documentation on how moderation works
- [ ] make a video demo for the public/website - nick
- [x] implement /actions and /roles commands -cblgh https://github.com/cabal-club/cabal-client/pull/52
- [ ] fix unintuitive moderation caveats https://github.com/cabal-club/cabal-cli/pull/190#discussion_r430021350, https://gist.github.com/cblgh/0912d6ec4872d974da29f752c56951b0
- [ ] unordered materialized-group-auth - substack

**Comment by substack** [comment]
# mozilla mvp cabal demo

## outline

0. brief intro about cabal and the subjective moderation system
1. as user A: create a new cabal
2. as user A: send a link to friends with user A as the mod
3. as user B (not presenting): post a spammy message
4. as user A: ban user B for being a spammer
5. as user C (not presenting): say that cats are good
6. as user A: ban user C for saying that cats are good
7. as user D: undo the previous ban from user A
8. as user E: set mod key to user D. show how user C reappears
9. as user E: add user C as a moderator
10. discuss findings from user research and cblgh thesis
11. close

## intro notes

* no servers, no accounts, offline and works over the internet or a local network
* longevity: infrastructure and social
* subjective moderation: everyone is an admin, from their perspective
* anyone can step up to perform moderation work
* when you share a link, you share a moderation key to ensure the new person will have a good onboarding experience

## logistics

* the presenter will have 3 accounts for users A, D, and E
* other team members not presenting will be users B and C
* presenter will use a mix of clients: desktop and cli
* other team members not presenting will join the cabal and add messages

**Comment by noffle** [comment]
I consolidated the remaining items (& more!) into a new tracking issue, now that work on the MVP is complete: https://github.com/cabal-club/commons/issues/12
